k8sImageAvailabilityExporter:
  image:
    repository: ghcr.io/webfleet-solutions/k8s-image-availability-exporter
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources: {}
  args:
    - --bind-address=:8080
  
serviceMonitor:
  enabled: false
  interval: 15s

prometheusRule:
  enabled: false
  defaultGroupsEnabled: true
  additionalGroups: []
